Update Mockito to allow tests to be run under Java 11
DevX has recommended that teams stop using Java 8 (see
https://docs.google.com/document/d/1ZR-YnaXCT5_gLVmTCeGs0mWd3KPaAozPjQK8uUzHZ9w/edit )
so it's good to get this project capable of running tests under Java 11!

The only blocker is the old version of Mockito, which would throw this error
when running tests under Java 11:

```
java.lang.UnsupportedOperationException: Cannot define class using reflection: Could not find sun.misc.Unsafe
```

It looks like Java 11 compatability was added to Mockito sometime around 2019
(see https://github.com/mockito/mockito/issues/1483 and
https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md)
so just upgrading to the latest version fixes the issue.

There's also a couple of changes to mocking-exceptions in the tests, as the later
version of Mockito is more strict - you can't say `thenThrow(classOf[Exception])`
if the exception is a checked-exception, and method you're mocking doesn't
actually throw that exception! So instead we just say `thenThrow(classOf[RuntimeException])`,
which is something any method can do at anytime, without having to declare it
in its signature.

```
[info] - should succeed with NO_CONTENT *** FAILED ***
[info]   org.mockito.exceptions.base.MockitoException: Mockito cannot mock this class: interface com.gu.atom.data.PreviewDataStore
[info]
[info] Mockito can only mock visible & non-final classes.
[info] If you're not sure why you're getting this error, please report to the mailing list.
[info]
[info] Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection: Could not find sun.misc.Unsafe
[info]   at org.scalatest.mockito.MockitoSugar.mock(MockitoSugar.scala:73)
[info]   at org.scalatest.mockito.MockitoSugar.mock$(MockitoSugar.scala:72)
[info]   at org.scalatest.mockito.MockitoSugar$.mock(MockitoSugar.scala:155)
[info]   at com.gu.atom.play.test.AtomSuite.previewDataStoreMockWithTestData(AtomSuite.scala:22)
[info]   at com.gu.atom.play.test.AtomSuite.previewDataStoreMockWithTestData$(AtomSuite.scala:21)
[info]   at com.gu.atom.play.test.AtomAPIActionsSpec.previewDataStoreMockWithTestData(AtomAPIActionsSpec.scala:15)
[info]   at com.gu.atom.play.test.AtomSuite.initialPreviewDataStore(AtomSuite.scala:53)
[info]   at com.gu.atom.play.test.AtomSuite.initialPreviewDataStore$(AtomSuite.scala:53)
[info]   at com.gu.atom.play.test.AtomAPIActionsSpec.initialPreviewDataStore(AtomAPIActionsSpec.scala:15)
[info]   at com.gu.atom.play.test.AtomSuite$AtomTestConf$.apply$default$1(AtomSuite.scala:73)
[info]   ...
[info]   Cause: java.lang.UnsupportedOperationException: Cannot define class using reflection: Could not find sun.misc.Unsafe
[info]   at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:334)
[info]   at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInjector.java:187)
[info]   at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:205)
[info]   at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:79)
[info]   at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4247)
[info]   at org.mockito.internal.creation.bytebuddy.MockBytecodeGenerator.generateMockClass(MockBytecodeGenerator.java:60)
[info]   at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.generate(CachingMockBytecodeGenerator.java:99)
[info]   at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.getOrGenerateMockClass(CachingMockBytecodeGenerator.java:89)
[info]   at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator.get(CachingMockBytecodeGenerator.java:37)
[info]   at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createProxyClass(ByteBuddyMockMaker.java:54)
[info]   ...
```